version: '3.8'
services:

  postgres:
    image: postgres:alpine3.18
    restart: always
    environment:
      POSTGRES_USER: django
      POSTGRES_PASSWORD: django
      POSTGRES_DB: events
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data

  events:
    build:
      context: ../
      dockerfile: Docker/Dockerfile
    command: >
      sh -c "python manage.py migrate --settings=event_management.settings_prod &&
             python manage.py createsuperuser --noinput --settings=event_management.settings_prod || true &&
             python manage.py runserver --settings=event_management.settings_prod 0.0.0.0:8000"
    volumes:
      - ../:/srv
    ports:
      - 8000:8000
    environment:
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=django
      - POSTGRES_NAME=events
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_PASSWORD=django
      - DJANGO_SUPERUSER_EMAIL=admin@example.com

volumes:
  postgres:
